yaricap = float(input("Yarı Çapı Giriniz: "))
pi = float(3)
print("Dairenin alanı")
daireninAlani = float(float(pi) *float( yaricap) * float(yaricap))
print("Dairenin Alanı:", daireninAlani)
print("Dairenin Çevresi")
cevre = float(float(2) * float(pi) * float(yaricap))
print("Dairenin Çevresi:", cevre)
